const courseData = {
    "UG": [
      {
        "name": "BCA",
        "full_name": "Bachelor of Computer Applications",
        "duration": "3 years",
        "type": "Undergraduate",
        "semesters": 6,
        "credits": 140,
        "credit_system": "CBCS",
        "grading_system": "10-point scale",
        "eligibility": "10+2 with Mathematics (50%)",
        "entrance_exam": false,
        "core_subjects": ["Programming", "DBMS", "Web Technologies"],
        "electives": ["AI", "Cloud Computing"],
        "practical_labs": 4,
        "internship": "6-month compulsory",
        "career_opportunities": ["Software Developer", "System Analyst"],
        "avg_salary": "4.5 LPA",
        "lab_facilities": ["Advanced Computing Lab", "Networking Lab"],
        "industry_tieups": ["IBM", "TCS"],
        "batch_size": 60,
        "last_updated": "2025-06-01"
      },
      {
        "name": "BCom",
        "full_name": "Bachelor of Commerce",
        "duration": "3 years",
        "type": "Undergraduate",
        "semesters": 6,
        "credits": 120,
        "credit_system": "Non-CBCS",
        "grading_system": "Percentage",
        "eligibility": "10+2 Commerce (45%)",
        "core_subjects": ["Accounting", "Business Law", "Economics"],
        "career_opportunities": ["Accountant", "Financial Analyst"],
        "avg_salary": "3.8 LPA",
        "lab_facilities": ["Accounting Lab"],
        "industry_tieups": ["Local Businesses"],
        "batch_size": 80,
        "last_updated": "2025-06-01"
      },
      {
        "name": "BBA",
        "full_name": "Bachelor of Business Administration",
        "duration": "3 years",
        "type": "Undergraduate",
        "semesters": 6,
        "credits": 132,
        "credit_system": "CBCS",
        "grading_system": "7-point scale",
        "eligibility": "10+2 Any Stream (50%)",
        "entrance_exam": false,
        "core_subjects": ["Marketing", "Finance", "HR Management"],
        "career_opportunities": ["Business Analyst", "Marketing Executive"],
        "avg_salary": "4.2 LPA",
        "internship": "3-month optional",
        "batch_size": 75,
        "last_updated": "2025-06-01"
      },
      {
        "name": "BSc CS",
        "full_name": "Bachelor of Science in Computer Science",
        "duration": "3 years",
        "type": "Undergraduate",
        "semesters": 6,
        "credits": 135,
        "credit_system": "CBCS",
        "grading_system": "10-point scale",
        "eligibility": "10+2 Science (55%)",
        "entrance_exam": false,
        "core_subjects": ["Algorithms", "Computer Networks", "OS"],
        "career_opportunities": ["Software Engineer", "Data Analyst"],
        "avg_salary": "5.0 LPA",
        "lab_facilities": ["Programming Lab", "Hardware Lab"],
        "batch_size": 50,
        "last_updated": "2025-06-01"
      }
    ],
    "PG": [
      {
        "name": "MSc CS",
        "full_name": "Master of Science in Computer Science",
        "duration": "2 years",
        "type": "Postgraduate",
        "semesters": 4,
        "credits": 90,
        "credit_system": "CBCS",
        "grading_system": "10-point scale",
        "eligibility": "BSc CS/BCA (55%)",
        "entrance_exam": true,
        "research_requirement": "Thesis submission",
        "core_subjects": ["Advanced Algorithms", "Machine Learning"],
        "career_opportunities": ["Research Scientist", "AI Engineer"],
        "avg_salary": "6.8 LPA",
        "batch_size": 40,
        "last_updated": "2025-06-01"
      },
      {
        "name": "MCA",
        "full_name": "Master of Computer Applications",
        "duration": "2 years",
        "type": "Postgraduate",
        "semesters": 4,
        "credits": 95,
        "credit_system": "Semester",
        "grading_system": "Percentage",
        "eligibility": "Graduation with Math (50%)",
        "entrance_exam": true,
        "core_subjects": ["Cloud Computing", "Big Data"],
        "career_opportunities": ["Cloud Architect", "Full Stack Developer"],
        "avg_salary": "6.5 LPA",
        "batch_size": 60,
        "last_updated": "2025-06-01"
      }
    ],
    "Diploma": [
      {
        "name": "PGDCA",
        "full_name": "Post Graduate Diploma in Computer Applications",
        "duration": "1 year",
        "type": "Diploma",
        "semesters": 2,
        "credits": 50,
        "credit_system": "Semester",
        "grading_system": "Percentage",
        "eligibility": "Graduation",
        "certification": "Microsoft Certified",
        "core_subjects": ["Basic Programming", "Office Tools"],
        "career_opportunities": ["IT Support", "Junior Developer"],
        "avg_salary": "3.0 LPA",
        "batch_size": 100,
        "last_updated": "2025-06-01"
      },
      {
        "name": "DCA",
        "full_name": "Diploma in Computer Applications",
        "duration": "6 months",
        "type": "Diploma",
        "semesters": 1,
        "credits": 25,
        "grading_system": "Pass/Fail",
        "eligibility": "10+2",
        "core_subjects": ["Computer Basics", "Internet"],
        "career_opportunities": ["Computer Operator"],
        "avg_salary": "2.0 LPA",
        "batch_size": 120,
        "last_updated": "2025-06-01"
      }
    ]
  }
  

  export default courseData;